CREATE SCHEMA IF NOT EXISTS library AUTHORIZATION postgres;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'app_user') THEN
CREATE ROLE app_user LOGIN PASSWORD 'app_user123';
END IF;
END$$;

GRANT CREATE, USAGE ON SCHEMA library TO app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA library
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA library
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO app_user;

ALTER ROLE app_user IN DATABASE library_db SET search_path = library, public;
