spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: library
      hibernate.format_sql: false
      hibernate.jdbc.time_zone: UTC

server:
  port: ${SERVER_PORT:8080}
